### ISSUE TITLE
Activity page

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/wallet#402]
When visiting the activity page on the browser I see some strange things:
* In my local console I see
```
SvelteKitError: Not found: /it/[object%20Object]
    at resolve (/home/matteo/src/wallet/node_modules/.pnpm/@sveltejs+kit@2.5.10_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.17_vite@5.2.12/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/home/matteo/src/wallet/node_modules/.pnpm/@sveltejs+kit@2.5.10_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.17_vite@5.2.12/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at Object.eval [as handle] (/home/matteo/src/wallet/node_modules/.pnpm/@inlang+paraglide-js-adapter-sveltekit@0.5.22_@sveltejs+kit@2.5.10_svelte@4.2.17/node_modules/@inlang/paraglide-js-adapter-sveltekit/dist/runtime/hooks/handle.js:23:16)
    at Module.respond (/home/matteo/src/wallet/node_modules/.pnpm/@sveltejs+kit@2.5.10_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.17_vite@5.2.12/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```
* On browser console I see:
![image](https://github.com/ForkbombEu/wallet/assets/102997993/cedc2aea-ef09-47ab-b26a-67c8a1101685)
![image](https://github.com/ForkbombEu/wallet/assets/102997993/70575bd8-590d-41fe-8e6c-7c8e1de8ceb1)
* The notification date is 54 years ago
* They have different shapes based on the text in it
![image](https://github.com/ForkbombEu/wallet/assets/102997993/cc23a9b8-2ccf-4b95-889d-c77ac0e2c7aa)

**Comment by puria** [comment]
Yes, all known... also sometimes when you push REMOVE it lock you out or send you to the HOME tab
